### ISSUE TITLE
Json Delete

### ISSUE THREAD

**Issue by joskar** [beders/Resty#24]
I am using Resty 0.3.2 on android  
I am calling delete like this : 
request.json("http://example.com:port/customer/4", delete());

here is the error , is my falut or Resty ?

02-26 00:10:56.736: W/System.err(1116): java.io.IOException: BufferedInputStream is closed
02-26 00:10:56.747: W/System.err(1116):     at java.io.BufferedInputStream.streamClosed(BufferedInputStream.java:118)
02-26 00:10:56.747: W/System.err(1116):     at java.io.BufferedInputStream.read(BufferedInputStream.java:279)
02-26 00:10:56.747: W/System.err(1116):     at java.io.InputStream.read(InputStream.java:163)
02-26 00:10:56.747: W/System.err(1116):     at us.monoid.web.AbstractResource.fill(AbstractResource.java:44)
02-26 00:10:56.757: W/System.err(1116):     at us.monoid.web.Resty.fillResourceFromURL(Resty.java:432)
02-26 00:10:56.757: W/System.err(1116):     at us.monoid.web.Resty.doPOSTOrPUT(Resty.java:394)
02-26 00:10:56.757: W/System.err(1116):     at us.monoid.web.Resty.json(Resty.java:223)
02-26 00:10:56.757: W/System.err(1116):     at us.monoid.web.Resty.json(Resty.java:228)
02-26 00:10:56.757: W/System.err(1116):     at com.example.resttest.RestTasks.doRequest(RestTasks.java:57)
02-26 00:10:56.757: W/System.err(1116):     at com.example.resttest.RestTasks.doInBackground(RestTasks.java:29)
02-26 00:10:56.757: W/System.err(1116):     at com.example.resttest.RestTasks.doInBackground(RestTasks.java:1)
02-26 00:10:56.767: W/System.err(1116):     at android.os.AsyncTask$2.call(AsyncTask.java:287)

02-26 00:10:56.767: W/System.err(1116):     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
02-26 00:10:56.767: W/System.err(1116):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
02-26 00:10:56.777: W/System.err(1116):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
02-26 00:10:56.777: W/System.err(1116):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
02-26 00:10:56.793: W/System.err(1116):     at java.lang.Thread.run(Thread.java:856)

EDIT: 
I am using all the others methods successful only the delete is creating this error

**Comment by zepernick** [comment]
I encountered this same error on a put.  Here is the code that is causing the error

`new Resty()
               .text(url + "/ViewingSession/" + getViewSessionId() + "/SourceFile?FileExtension=" + extension,
                       Resty.put(
                               Resty.content(
                                        IOUtils.toByteArray(new FileInputStream(documentFile))
                               )
                       )
                );`

The same error happens whether it is using json, text, or bytes.  The relevant piece of the stack trace is below.

`java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:151)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at us.monoid.web.AbstractResource.fill(AbstractResource.java:44)
    at us.monoid.web.Resty.fillResourceFromURL(Resty.java:432)
    at us.monoid.web.Resty.doPOSTOrPUT(Resty.java:394)
    at us.monoid.web.Resty.bytes(Resty.java:383)
    at us.monoid.web.Resty.bytes(Resty.java:371)
    at com.iws.actions.document.master.MasterDocumentPopulateAction.doPopulate(MasterDocumentPopulateAction.java:87)`

The response being sent back from the service is empty per the documentation for the service.  I am guessing that may have something to do with it.

**Comment by zepernick** [comment]
This looks like it has been corrected in the current master branch.  There was a error happening when reading the error stream in.  There is a try / catch there now that ignores the error and writes a warn to the log.
